#+DESCRIPTION: Concurrent data structures for C++
#+AUTHOR: Justin Andreas Lacoste
*jt* is a lightweight, single-header library that provides convenient concurrent data structures designed for efficient multi-threaded programming.

*Note*: This library requires at least C++20.

* Features

** Multi-Producer / Single-Consumer (MPSC)

The MPSC (Multi-Producer, Single-Consumer) implementation allows
multiple threads to safely enqueue data while others wait for it.

Unlike the name, this library allows for multiple threads to safely
~wait~ on the consumer. Effectively transforming the queue into a
work-stealing queue.

- *Example*: Check out the [[examples/thread_pool.cpp][thread pool example]] to see how to utilize
  the MPSC queue.

** Single-Producer / Multi-Consumer (SPMC)

The SPMC (Single-Producer, Multi-Consumer) implementation employs a
publish-subscribe pattern, enabling a single producer to distribute
data to multiple consumers. This is particularly useful for scenarios
where you want to broadcast messages or events to several listeners.

* Getting Started
** Manually
Simply copy the ~jt.hpp~ header and include it in your source code.

** CMake
To get started using ~jt~ with CMake, add the repository somewhere
into your project, i.e. ~third_party/jt~ and then use:

#+BEGIN_SRC cmake
  set(JT_BUILD_EXAMPLES OFF)
  add_subdirectory(third_party/jt)
  target_link_libraries(<your-executable> PRIVATE jt)
#+END_SRC

* Documentation

There currently is no documentation, refer to either the source-code
in ~jt.hpp~, or look at the ~examples/~.

* Usage

Refer to the examples provided in the ~examples~ directory for
practical usage patterns.

* License

This project is licensed under the MIT License. See the [[LICENSE][LICENSE]] file
for details.
